import type { Db } from "mongodb";
import { mongodbAdapter } from "unadapter/mongodb";
import { createUnadapterStorage } from "./unadapter";

/** Options for {@link mongodbStorage}. */
export interface MongodbStorageOptions {
	/** Use string ids generated by MessageWeave or UUID ids. */
	idStrategy?: "string" | "uuid";
}

/** Create MessageWeave storage backed by a MongoDB database. */
export function mongodbStorage(db: Db, options?: MongodbStorageOptions) {
	return createUnadapterStorage(mongodbAdapter(db), options?.idStrategy);
}
