import type { Db } from "mongodb";
import { mongodbAdapter as unadapterMongodb } from "unadapter/mongodb";
import { createUnadapterStorage } from "./unadapter";

/** Options for {@link mongodbAdapter}. */
export interface MongodbAdapterOptions {
	/** Use string ids generated by MessageWeave or UUID ids. */
	idStrategy?: "string" | "uuid";
}

/** Create MessageWeave storage backed by a MongoDB database. */
export function mongodbAdapter(db: Db, options?: MongodbAdapterOptions) {
	return createUnadapterStorage(unadapterMongodb(db), options?.idStrategy);
}
