/**
 * A JSON-serializable value. Used for schema-less event content and room
 * metadata payloads.
 */
export type JsonValue =
	| string
	| number
	| boolean
	| null
	| JsonValue[]
	| { [key: string]: JsonValue };

/** A JSON object payload. */
export type JsonObject = { [key: string]: JsonValue };

/** Broad media category used by {@link AttachmentReference}. */
export type AttachmentKind = "image" | "video" | "audio" | "file";

/**
 * Host-owned attachment metadata that can be embedded in event content.
 *
 * `id` is an opaque identifier. ChatCore stores and synchronizes the reference,
 * but deliberately does not upload, download, authorize, or delete the
 * underlying file. The host application resolves the identifier and owns the
 * complete attachment lifecycle.
 */
export type AttachmentReference = JsonObject & {
	/** Opaque attachment identifier issued by the host application. */
	id: string;
	/** Broad media category used by clients for presentation. */
	kind: AttachmentKind;
	/** Original filename, when the host chooses to expose it. */
	name?: string;
	/** Declared or detected MIME type. */
	mimeType?: string;
	/** File size in bytes. */
	size?: number;
	/** Pixel width for visual media. */
	width?: number;
	/** Pixel height for visual media. */
	height?: number;
	/** Playback duration in milliseconds for audio or video. */
	durationMs?: number;
};

/**
 * The atomic, immutable unit of state in ChatCore. Once written, a
 * `FlowEvent` is never updated or deleted — the historical state of a room is
 * computed by replaying its events.
 */
export interface FlowEvent {
	/** Unique identifier generated by the storage backend. */
	id: string;
	/** Identifier of the isolated conversation boundary this event belongs to. */
	roomId: string;
	/** The entity that initiated the event. */
	senderId: string;
	/** Dot-notated namespace identifier, e.g. `message.text`, `room.state.name`. */
	type: string;
	/**
	 * When present (including the empty string), marks this as a "state event"
	 * representing durable room configuration rather than transient timeline
	 * traffic.
	 */
	stateKey: string | null;
	/** Schema-less JSON payload carrying event-specific data. */
	content: JsonObject;
	/** Creation time, epoch milliseconds. */
	timestamp: number;
	/**
	 * Strictly-increasing, globally unique sequential integer assigned at
	 * publish time. Drives real-time synchronization.
	 */
	sequenceId: number;
}

/** An isolated chat boundary. */
export interface Room {
	/** Unique identifier generated by the storage backend. */
	id: string;
	/** Identifier of the entity that created the room. */
	creatorId: string;
	/** Creation time, epoch milliseconds. */
	createdAt: number;
	/** Schema-less JSON metadata supplied by the host application. */
	metadata: JsonObject;
}

/** A parent → child link between two events (threading / DAG). */
export interface EventEdge {
	/** Identifier of the child event. */
	eventId: string;
	/** Identifier of the parent event. */
	parentEventId: string;
}

/** Input for {@link ChatCore.createRoom}. */
export interface CreateRoomInput {
	/** Identifier of the entity creating the room. */
	creatorId: string;
	/** Optional host-defined room metadata. */
	metadata?: JsonObject;
}

/** Options for {@link ChatCore.listRooms}. */
export interface ListRoomsOptions {
	/**
	 * Maximum number of rooms to return.
	 *
	 * @default ChatCoreOptions.defaultLimit
	 */
	limit?: number;
	/**
	 * Sort direction by room creation time.
	 *
	 * @default "asc"
	 */
	order?: "asc" | "desc";
}

/** Input for {@link ChatCore.publishEvent}. */
export interface PublishEventInput {
	/** Room that receives the event. */
	roomId: string;
	/** Entity publishing the event. */
	senderId: string;
	/** Dot-notated event namespace such as `message.text`. */
	type: string;
	/**
	 * Marks the event as a state event and upserts the room-state projection
	 * under the composite key `[roomId, type, stateKey]`. The empty string is a
	 * valid state key.
	 */
	stateKey?: string;
	/** Schema-less event payload. */
	content?: JsonObject;
	/** Parent event ids, persisted as edges for threading / replies. */
	parentEventIds?: string[];
}

/** Input for {@link ChatCore.sendMessage}. */
export interface SendMessageInput {
	/** Room that receives the message. */
	roomId: string;
	/** Entity sending the message. */
	senderId: string;
	/** Message body. Whitespace-only messages are rejected. */
	body: string;
	/** Parent event ids when sending a reply. */
	parentEventIds?: string[];
}

/** Input for {@link ChatCore.editMessage}. */
export interface EditMessageInput {
	/** Room containing the message being edited. */
	roomId: string;
	/** Entity performing the edit. */
	senderId: string;
	/** Identifier of the message event being edited. */
	messageId: string;
	/** Updated message body. Whitespace-only messages are rejected. */
	body: string;
	/** Optional additional JSON metadata for the edit event. */
	content?: JsonObject;
}

/** Input for {@link ChatCore.deleteMessage}. */
export interface DeleteMessageInput {
	/** Room containing the message being deleted. */
	roomId: string;
	/** Entity performing the deletion. */
	senderId: string;
	/** Identifier of the message event being deleted. */
	messageId: string;
	/** Optional reason or metadata explaining the deletion. */
	reason?: string;
	/** Optional additional JSON metadata for the delete event. */
	content?: JsonObject;
}

/** Result of {@link ChatCore.publishEvent}. */
export interface PublishEventResult {
	/** Persisted event. */
	event: FlowEvent;
	/** Global sequence assigned to the event. */
	sequenceId: number;
}

/** Options for {@link ChatCore.getRoomTimeline}. */
export interface GetTimelineOptions {
	/** Maximum number of events to return. */
	limit?: number;
	/** Return only events strictly before this sequence id (for pagination). */
	beforeSequenceId?: number;
}

/** Options for {@link ChatCore.getSyncStream}. */
export interface GetSyncStreamOptions {
	/** Return only events with `sequenceId` strictly greater than this token. */
	sinceSequenceId?: number;
	/** Maximum number of events to return. */
	limit?: number;
	/**
	 * Restrict the stream to these rooms. The host resolves which rooms the
	 * caller may observe from its own auth and passes them here.
	 *
	 * - Omitted → full global stream (back-compat for single-tenant embeds).
	 * - `[]` → returns no events.
	 * - `[...]` → returned events are filtered with `roomId IN (...)`.
	 *
	 * For scoped streams, ChatCore also reads a global page boundary to advance
	 * `nextToken` across out-of-scope sequence gaps. This means out-of-scope
	 * events are not returned, but their sequence positions can affect the resume
	 * token.
	 *
	 * **Scale note (v0.2):** `roomId IN (...)` is acceptable for moderate room
	 * sets. High-fan-out actors (thousands of rooms) may benefit from a
	 * per-room cursor approach, tracked as a follow-up.
	 */
	roomIds?: string[];
}

/** Result of {@link ChatCore.getSyncStream}. */
export interface SyncStreamResult {
	/** Events after the requested cursor, ordered oldest first. */
	events: FlowEvent[];
	/**
	 * Resume token for the next call. For global streams this is the last
	 * returned event sequence id. For scoped streams this may also advance to the
	 * global page boundary so clients do not repeatedly scan out-of-scope gaps.
	 */
	nextToken: number;
}

/**
 * A UI-ready presentation message computed by folding raw event streams
 * (including edits, reactions, and deletions).
 */
export interface ProjectedMessage {
	/** Identifier of the root message event. */
	id: string;
	/** Conversation room identifier. */
	roomId: string;
	/** Entity that originally sent the message. */
	senderId: string;
	/** Message event type (typically `message.text`). */
	type: string;
	/** Current effective message body text. Empty string if deleted. */
	body: string;
	/** Merged effective event content payload. */
	content: JsonObject;
	/** Original message creation timestamp in epoch milliseconds. */
	timestamp: number;
	/** Sequence ID of the original message event. */
	sequenceId: number;
	/** Whether this message has been edited at least once. */
	isEdited: boolean;
	/** Timestamp of the most recent edit in epoch milliseconds, or `null`. */
	editedAt: number | null;
	/** Sequence ID of the most recent edit, or `null`. */
	lastEditSequenceId: number | null;
	/** Whether this message has been deleted / tombstoned. */
	isDeleted: boolean;
	/** Timestamp when the message was deleted in epoch milliseconds, or `null`. */
	deletedAt: number | null;
	/** Deletion reason if provided, or `null`. */
	deleteReason: string | null;
	/** Number of times this message was edited. */
	editCount: number;
	/** The root message event and all revision/tombstone events linked to it. */
	rawEvents: FlowEvent[];
}

/** Options for {@link projectTimeline}. */
export interface ProjectTimelineOptions {
	/**
	 * When true (default), deleted messages are included in the projected result
	 * with `isDeleted: true` and empty/tombstone body.
	 * When false, deleted messages are filtered out of the output array.
	 *
	 * @default true
	 */
	includeDeleted?: boolean;
}
